EIP1: Review 1 Import Register Checker API Codebase and Project Setup
communitiesuk/eip-ero-ems-integration-api pull request #113
Opened 2024-12-04 10:33 UTC by SimPaySW

Part of [EIP1-11113](https://mhclgdigital.atlassian.net/browse/EIP1-11113)

The feature commits on this branch cover import of the Register Cheker API project setup, gradle, software versions (SB3 etc). as well as the commits under EIP1-11111 as the db migrations are a pre-requisite to this code working.

2025-02-03 14:04 UTC, tomsdjohnson reviewed
Just a few preliminary questions

2025-02-03 14:04 UTC, tomsdjohnson commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/ApiProperties.kt
the "database" subfolder that is present in the eip-ero-register-checker-api  that has "ReplicaAwareTransactionManager" and "TransactonRoutingDataSource" files is missing from this config file. Is there a reason they were left out or are they needed here to?

2025-02-03 14:34 UTC, tomsdjohnson requested changes

2025-02-03 14:34 UTC, tomsdjohnson commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/mapper/RegisterCheckResultMapper.kt
> +abstract class RegisterCheckResultMapper {
I think we should only be using mapstruct.Mappings for Enums mappings done to from Api, Dto, and etity objects should be manual

2025-02-03 14:34 UTC, tomsdjohnson commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/mapper/RegisterCheckResultMapper.kt
> +abstract class RegisterCheckResultMapper {
if you see the Mappers section of docs/guidelines/general.md in the applications API, we should be using those guidelines, and updating prexisitng mappers where we can

2025-02-03 14:36 UTC, tomsdjohnson commented on owasp.suppressions.xml
> -    <suppress until="2024-05-03Z">
It's either include them here or bump the springboot version to where these are no longer issues

2025-02-03 14:43 UTC, tomsdjohnson requested changes

2025-02-03 14:43 UTC, tomsdjohnson commented on src/main/resources/openapi/EMSIntegrationAPIs.yaml
As per the ticket:

RegisterCheckerAPI.yaml should be copied across alongside the EMSIntegrationAPI.yaml and not renamed/altered

2025-02-04 13:54 UTC, SimPaySW commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/mapper/RegisterCheckResultMapper.kt
> +abstract class RegisterCheckResultMapper {
Thanks, it's a valid point, although this work was done before that guidance appeared.  I could to raise a ticket to upgrade the merged service to the latest coding standards, and schedule it to be done after this work has been merged. I'm just keen to keep the review and merge process simple if possible

2025-02-04 13:56 UTC, SimPaySW commented on src/main/resources/db/changelog/db.changelog-master.yaml
> -      file: db/changelog/create/0023_EIP1-11198_add-is-from-applications-api-flag.xml
The aim of the `isFromApplicationsApi` flag is to give a marker on the portal that applications are from the service apis or applications api.  It isn't needed by the EMS api.

2025-02-04 14:04 UTC, SimPaySW commented on owasp.suppressions.xml
> -    <suppress until="2024-05-03Z">
Yes we are using SB 3.3.5 which brings in QOS 1.5.11 so is vulnerable.  I will re-add these back, and look into upgrading SB to 3.3.8 or later.

2025-02-04 14:13 UTC, SimPaySW commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/RegisterCheckerApiApplication.kt
> +    runApplication<RegisterCheckerApiApplication>(*args)
I've made it like that in the final increment of this dev effort e.g. [review 5](https://github.com/communitiesuk/eip-ero-ems-integration-api/blob/EIP1-11114-review-5-add-archiving-queue/src/main/kotlin/uk/gov/dluhc/emsintegrationapi/EmsIntegrationApiApplication.kt).

2025-02-04 14:22 UTC, SimPaySW commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/client/ElectoralRegistrationOfficeManagementApiClient.kt
> -package uk.gov.dluhc.emsintegrationapi.client
We definitely do!  It's the way I have put these PRs together.  The main code is added back in as part of [review 3](https://github.com/communitiesuk/eip-ero-ems-integration-api/pull/119/files).

2025-02-04 14:30 UTC, SimPaySW commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/RegisterCheckerHeaderAuthenticationFilter.kt
> +class RegisterCheckerHeaderAuthenticationFilter(
Change covered by [review 3](https://github.com/communitiesuk/eip-ero-ems-integration-api/pull/119/files#diff-7c2e0fa4faec50d5b5f0091bf8f4b1a3d6c36489f9be88b3fcfe0218b29c6995).

2025-02-04 14:43 UTC, tomsdjohnson commented on src/main/kotlin/uk/gov/dluhc/emsintegrationapi/mapper/RegisterCheckResultMapper.kt
> +abstract class RegisterCheckResultMapper {
Yup if you could raise a new ticket for doing this as part of this that would be great

2025-03-17 13:16 UTC, closed without merging